services:
  server:
    image: ${IMAGE_NAME}:latest
    container_name: "server"
    environment:
      PORT: 8080
      HOST: 0.0.0.0
      PACK_BOXES: 250,500,1000,2000,5000
      LOG_LEVEL: DEBUG
      LOG_FORMAT: text
    ports:
      - "8080:8080"
